version: '2'
services:
  roscore:
    image: tech-sketch/roscore
    container_name: roscore
    hostname: roscore
    command:
      - roscore
  rosbridge:
    image: tech-sketch/rosbridge
    container_name: rosbridge
    hostname: rosbridge
    depends_on:
      - roscore
    environment:
      - ROS_HOSTNAME=rosbridge
      - ROS_MASTER_URI=http://${master}:11311
      - MQTT_HOST=mqtt.tech-sketch.jp
      - MQTT_PORT=8883
      - MQTT_USERNAME=ros
      - MQTT_PASSWORD=${mqtt_password}
    command:
      - /opt/entrypoint.sh
